name: WakaTime Readme

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          COMMIT_MESSAGE: "chore: update wakatime"
          TIME_RANGE: last_7_days
          SHOW_TOTAL: true